### ISSUE TITLE
1.0.3 is latest now

### ISSUE THREAD

**Issue by alexellis** [stefanprodan/istio-gke#2]
Hi Stefan,

Just an FYI, but you'll get 1.0.3 installed from the Istio get script now over at: https://github.com/stefanprodan/istio-gke/blob/master/docs/istio/04-istio-setup.md

It'd be good if you could update the instructions but it's not too hard to figure out otherwise.

I also got this error while deploying with helm:

```
helm upgrade --install istio ./install/kubernetes/helm/istio --namespace=istio-system -f ./my-istio.yaml
Release "istio" does not exist. Installing it now.
Error: apiVersion "config.istio.io/v1alpha2" in istio/charts/mixer/templates/config.yaml is not available
```

Alex

**Comment by alexellis** [comment]
Looks like the CRD is needed with helm less than 2.10.0 - https://istio.io/docs/setup/kubernetes/helm-install/#installation-steps

**Comment by alexellis** [comment]
Cheers 👍

**Comment by stefanprodan** [comment]
thanks for the heads up :)
