### ISSUE TITLE
istio-ingressgateway-certs

### ISSUE THREAD

**Issue by Karnich** [stefanprodan/istio-gke#5]
Hi Stefan

Ive installed using 1.1.0.RC2

im unable to get the certificates working. What exactly is supposed to create istio-ingressgateway-certs secret? Im not getting one created. :/

**Comment by stefanprodan** [comment]
You have to create a [public gateway](https://github.com/stefanprodan/istio-gke/blob/master/docs/istio/05-letsencrypt-setup.md#configure-istio-gateway-with-lets-encrypt-wildcard-certificate) before the cert-manager issuer, otherwise the cert-manager will not find the secret.
