### ISSUE TITLE
fail to install istio via helm

### ISSUE THREAD

**Issue by victory1908** [stefanprodan/istio-gke#8]
Hi,

With the latest istio 

follow `https://github.com/stefanprodan/istio-gke/blob/master/docs/istio/04-istio-setup.md`

we're receiving this error

```
Error: validation failed: unable to recognize "": no matches for kind "ClusterIssuer" in version "certmanager.k8s.io/v1alpha1"
``` 

after manage to install cert-manager, at step expose service `grafana`
```
https://github.com/stefanprodan/istio-gke/blob/master/docs/istio/06-grafana-config.md
```
when access `grafana` there is an error

```
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```
Can help review the installation and setup step. thanks!

**Comment by stefanprodan** [comment]
This guide needs a lot of changes to work with the latest Istio, I assume you are referring to 1.1.9 and not 1.2 RC. Next week I'll have time to make the upgrades.

**Comment by victory1908** [comment]
Thanks looking forward to the update. I'm referring to 1.2 RC. This is would be great if the update cover `Secret Discovery Service (SDS).` and also touch some `authentication` and `authorization` .
